-- Seed the 8 legacy products into D1 (generated from src/data/products.ts).
-- Idempotent-ish: clears the catalog first so re-running is safe in dev.
DELETE FROM product_images;
DELETE FROM products;

INSERT INTO products (id, slug, sku, name_es, name_en, name_fr, description_es, description_en, description_fr, category_es, category_en, category_fr, price, price_usd, badge, sizes, in_stock, featured, visible, sort_order) VALUES (1, 'camiseta-palenque-2020', 'AFR-ROP-CP20-01', 'Camiseta Palenque 2020', 'Palenque 2020 T-Shirt', 'T-shirt Palenque 2020', 'Camiseta edición especial Palenque 2020. Un diseño icónico que celebra la historia y la resistencia cultural.', 'Special edition Palenque 2020 T-shirt. An iconic design celebrating history and cultural resistance.', 'T-shirt édition spéciale Palenque 2020. Un design emblématique célébrant l''histoire et la résistance culturelle.', 'ropa', 'clothing', 'vêtements', 119900, 30, 'Premium', 'S,M,L,XL', 1, 1, 1, 0);
INSERT INTO product_images (product_id, r2_key, content_type, alt, position) VALUES (1, 'products/camiseta-palenque-2020/main.webp', 'image/webp', 'Camiseta Palenque 2020', 0);

INSERT INTO products (id, slug, sku, name_es, name_en, name_fr, description_es, description_en, description_fr, category_es, category_en, category_fr, price, price_usd, badge, sizes, in_stock, featured, visible, sort_order) VALUES (10, 'camiseta-afroin-classic', 'AFR-ROP-CAC-10', 'Camiseta Clásica AFRO IN', 'AFRO IN Classic T-Shirt', 'T-shirt Classique AFRO IN', 'Nuestra camiseta insignia. Diseño limpio y moderno con el logo AFRO IN. Calidad premium para uso diario.', 'Our flagship t-shirt. Clean and modern design with the AFRO IN logo. Premium quality for everyday use.', 'Notre t-shirt emblématique. Design épuré et moderne avec le logo AFRO IN. Qualité premium pour un usage quotidien.', 'ropa', 'clothing', 'vêtements', 89900, 23, 'Bestseller', 'S,M,L,XL', 1, 1, 1, 1);
INSERT INTO product_images (product_id, r2_key, content_type, alt, position) VALUES (10, 'products/camiseta-afroin-classic/main.webp', 'image/webp', 'Camiseta Clásica AFRO IN', 0);

INSERT INTO products (id, slug, sku, name_es, name_en, name_fr, description_es, description_en, description_fr, category_es, category_en, category_fr, price, price_usd, badge, sizes, in_stock, featured, visible, sort_order) VALUES (9, 'camiseta-negra-basica', 'AFR-ROP-CNB-09', 'Camiseta Negra AFRO IN', 'AFRO IN Black T-Shirt', 'T-shirt Noir AFRO IN', 'Camiseta negra esencial. Cómoda, duradera y con el estilo inconfundible de AFRO IN.', 'Essential black t-shirt. Comfortable, durable, and with the unmistakable AFRO IN style.', 'T-shirt noir essentiel. Confortable, durable et avec le style inimitable d''AFRO IN.', 'ropa', 'clothing', 'vêtements', 69900, 18, NULL, 'S,M,L,XL', 1, 0, 1, 2);
INSERT INTO product_images (product_id, r2_key, content_type, alt, position) VALUES (9, 'products/camiseta-negra-basica/main.webp', 'image/webp', 'Camiseta Negra AFRO IN', 0);

INSERT INTO products (id, slug, sku, name_es, name_en, name_fr, description_es, description_en, description_fr, category_es, category_en, category_fr, price, price_usd, badge, sizes, in_stock, featured, visible, sort_order) VALUES (8, 'gorra-sencilla', 'AFR-ACC-GSE-08', 'Gorra Sencilla', 'Simple Cap', 'Casquette Simple', 'Visera deportiva ligera y cómoda. Perfecta para protegerte del sol con estilo.', 'Lightweight and comfortable sports visor. Perfect for protecting yourself from the sun with style.', 'Visière de sport légère et confortable. Parfaite pour vous protéger du soleil avec style.', 'gorras', 'caps', 'casquettes', 59900, 15, NULL, NULL, 1, 0, 1, 3);
INSERT INTO product_images (product_id, r2_key, content_type, alt, position) VALUES (8, 'products/gorra-sencilla/main.webp', 'image/webp', 'Gorra Sencilla', 0);

INSERT INTO products (id, slug, sku, name_es, name_en, name_fr, description_es, description_en, description_fr, category_es, category_en, category_fr, price, price_usd, badge, sizes, in_stock, featured, visible, sort_order) VALUES (13, 'gorra-cafe', 'AFR-ACC-GRC-13', 'Gorra Café', 'Brown Cap', 'Casquette Marron', 'Gorra de alta calidad en tono café. Bordado premium y ajuste perfecto.', 'High-quality brown cap. Premium embroidery and perfect fit.', 'Casquette marron de haute qualité. Broderie premium et ajustement parfait.', 'gorras', 'caps', 'casquettes', 99999, 25, 'Nuevo', NULL, 1, 1, 1, 4);
INSERT INTO product_images (product_id, r2_key, content_type, alt, position) VALUES (13, 'products/gorra-cafe/main.jpeg', 'image/jpeg', 'Gorra Café', 0);

INSERT INTO products (id, slug, sku, name_es, name_en, name_fr, description_es, description_en, description_fr, category_es, category_en, category_fr, price, price_usd, badge, sizes, in_stock, featured, visible, sort_order) VALUES (14, 'gorra-negra', 'AFR-ACC-GRN-14', 'Gorra Negra', 'Black Cap', 'Casquette Noire', 'La gorra negra definitiva de AFRO IN. Elegante, versátil y con acabados de primera.', 'The definitive AFRO IN black cap. Elegant, versatile, and with top-notch finishes.', 'La casquette noire définitive d''AFRO IN. Élégante, polyvalente et aux finitions soignées.', 'gorras', 'caps', 'casquettes', 89999, 23, 'Popular', NULL, 1, 1, 1, 5);
INSERT INTO product_images (product_id, r2_key, content_type, alt, position) VALUES (14, 'products/gorra-negra/main.jpeg', 'image/jpeg', 'Gorra Negra', 0);

INSERT INTO products (id, slug, sku, name_es, name_en, name_fr, description_es, description_en, description_fr, category_es, category_en, category_fr, price, price_usd, badge, sizes, in_stock, featured, visible, sort_order) VALUES (15, 'termo-afroin', 'AFR-ACC-TER-15', 'Termo AFRO IN 90', 'AFRO IN 90 Thermos', 'Thermos AFRO IN 90', 'Mantén tus bebidas a la temperatura perfecta con nuestro termo exclusivo AFRO IN.', 'Keep your drinks at the perfect temperature with our exclusive AFRO IN thermos.', 'Gardez vos boissons à la température idéale avec notre thermos exclusif AFRO IN.', 'accesorios', 'accessories', 'accessoires', 89999, 23, 'Nuevo', NULL, 1, 1, 1, 6);
INSERT INTO product_images (product_id, r2_key, content_type, alt, position) VALUES (15, 'products/termo-afroin/main.jpeg', 'image/jpeg', 'Termo AFRO IN 90', 0);

INSERT INTO products (id, slug, sku, name_es, name_en, name_fr, description_es, description_en, description_fr, category_es, category_en, category_fr, price, price_usd, badge, sizes, in_stock, featured, visible, sort_order) VALUES (16, 'mug-afroin', 'AFR-ACC-MUG-16', 'Mug AFRO IN', 'AFRO IN Mug', 'Mug AFRO IN', 'Disfruta de tu café con estilo. Mug de cerámica de alta calidad con diseño AFRO IN.', 'Enjoy your coffee with style. High-quality ceramic mug with AFRO IN design.', 'Savourez votre café avec style. Mug en céramique de haute qualité au design AFRO IN.', 'accesorios', 'accessories', 'accessoires', 55000, 14, NULL, NULL, 1, 1, 1, 7);
INSERT INTO product_images (product_id, r2_key, content_type, alt, position) VALUES (16, 'products/mug-afroin/main.jpeg', 'image/jpeg', 'Mug AFRO IN', 0);

